[package]
name = "fine-lncs"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["jozott"]
description = "An Springer's Lecture Notes in Computer Science (LNCS) styled template."
homepage = "https://github.com/Jozott00/typst-fine-lncs"
repository = "https://github.com/Jozott00/typst-fine-lncs"
keywords = [
    "LLNCS",
    "LNCS",
    "paper",
    "Lecture Notes in Computer Science",
    "Springer",
    "Computer Science",
]
categories = ["paper"]
disciplines = ["computer-science"]
exclude = ["tests"]
license = "MIT"

[template]
path = "template"
entrypoint = "template/main.typ"
thumbnail = "thumbnail.png"

[tool]
